development:
  adapter: postgresql
  database: rapid-response_development
  host: localhost

test:
  adapter: postgresql
  database: rapid-response_test
  host: localhost

production:
  adapter: postgresql
  database: rapid-response_production
  host: localhost
